/**
 * The four wrecks.
 *
 * `phys` values feed the Rapier raycast-vehicle directly.
 * `body` values drive the procedural mesh builder.
 * `stats` is purely for the 0-10 bars on the menu.
 */

export const CAR_TYPES = [
  {
    id: 'ripsaw',
    name: 'RIPSAW',
    klass: 'muscle',
    color: 0xff4d2a,
    blurb: 'Big angry V8 in a steel brick. Does everything well, excuses nothing. Start here.',
    phys: {
      mass: 1250,
      engineForce: 5600,
      brakeForce: 190,
      reverseForce: 2600,
      maxSteer: 0.58,
      steerSpeed: 3.4,
      topSpeed: 52,          // m/s soft cap
      frictionSlip: 2.3,
      sideFriction: 1.05,
      suspensionStiffness: 32,
      suspensionTravel: 0.34,
      suspensionDamp: 0.45,
      suspensionRelax: 0.88,
      wheelRadius: 0.525,
      airControl: 1.0,
      jumpImpulse: 1.05,
      dashImpulse: 1.0,
      armor: 1.0,            // damage divisor — higher = tougher
      ramPower: 1.05,        // damage multiplier dealt to others
      boostMax: 100,
      boostDrain: 30,
      boostRegen: 11,
      boostForce: 26000,
      downforce: 9.0,
    },
    body: {
      w: 1.275, h: 0.425, l: 2.6875,     // half-extents of the collider
      ride: 1.0,
      track: 1.175, front: 1.8125, rear: -1.775,
      style: 'muscle',
      cabin: { w: 1.0, h: 0.375, l: 1.1875, z: -0.22, y: 0.60 },
      hoodScoop: true,
    },
    stats: { SPEED: 7, ACCEL: 7, GRIP: 7, ARMOUR: 6, AIR: 6 },
  },

  {
    id: 'hornet',
    name: 'HORNET',
    klass: 'stunt buggy',
    color: 0xffd23f,
    blurb: 'Feather-light tube frame with silly air control. Flips for fun, folds like a can.',
    phys: {
      mass: 860,
      engineForce: 4300,
      brakeForce: 150,
      reverseForce: 2100,
      maxSteer: 0.68,
      steerSpeed: 4.4,
      topSpeed: 47,
      frictionSlip: 2.5,
      sideFriction: 1.15,
      suspensionStiffness: 26,
      suspensionTravel: 0.46,
      suspensionDamp: 0.40,
      suspensionRelax: 0.80,
      wheelRadius: 0.55,
      airControl: 1.7,
      jumpImpulse: 1.35,
      dashImpulse: 1.25,
      armor: 0.62,
      ramPower: 0.8,
      boostMax: 120,
      boostDrain: 26,
      boostRegen: 15,
      boostForce: 24000,
      downforce: 6.0,
    },
    body: {
      w: 1.15, h: 0.35, l: 2.275,
      ride: 1.075,
      track: 1.275, front: 1.6, rear: -1.55,
      style: 'buggy',
      cabin: { w: 0.775, h: 0.375, l: 0.875, z: -0.10, y: 0.52 },
      rollCage: true,
      exposedWheels: true,
    },
    stats: { SPEED: 6, ACCEL: 8, GRIP: 8, ARMOUR: 3, AIR: 10 },
  },

  {
    id: 'mauler',
    name: 'MAULER',
    klass: 'monster truck',
    color: 0x46e08a,
    blurb: 'Two and a half tonnes of bad idea. Slow to wind up, but it drives THROUGH people.',
    phys: {
      mass: 2600,
      engineForce: 9600,
      brakeForce: 300,
      reverseForce: 4600,
      maxSteer: 0.50,
      steerSpeed: 2.6,
      topSpeed: 44,
      frictionSlip: 2.1,
      sideFriction: 0.92,
      suspensionStiffness: 30,
      suspensionTravel: 0.60,
      suspensionDamp: 0.50,
      suspensionRelax: 0.95,
      wheelRadius: 0.9,
      airControl: 0.62,
      jumpImpulse: 0.82,
      dashImpulse: 0.75,
      armor: 2.15,
      ramPower: 1.75,
      boostMax: 80,
      boostDrain: 34,
      boostRegen: 9,
      boostForce: 40000,
      downforce: 5.0,
    },
    body: {
      w: 1.45, h: 0.55, l: 2.8125,
      ride: 1.75,
      track: 1.525, front: 1.9375, rear: -1.9,
      style: 'truck',
      cabin: { w: 1.175, h: 0.525, l: 1.3125, z: 0.10, y: 0.80 },
      exposedWheels: true,
      bullbar: true,
    },
    stats: { SPEED: 5, ACCEL: 5, GRIP: 5, ARMOUR: 10, AIR: 3 },
  },

  {
    id: 'volt',
    name: 'VOLT',
    klass: 'hyper EV',
    color: 0x22e0ff,
    blurb: 'Silent, instant, glued to the floor. Endless boost — but one good hit ruins it.',
    phys: {
      mass: 1060,
      engineForce: 6400,
      brakeForce: 210,
      reverseForce: 3000,
      maxSteer: 0.62,
      steerSpeed: 4.0,
      topSpeed: 58,
      frictionSlip: 2.75,
      sideFriction: 1.30,
      suspensionStiffness: 38,
      suspensionTravel: 0.26,
      suspensionDamp: 0.48,
      suspensionRelax: 0.92,
      wheelRadius: 0.475,
      airControl: 1.25,
      jumpImpulse: 1.0,
      dashImpulse: 1.15,
      armor: 0.78,
      ramPower: 0.92,
      boostMax: 150,
      boostDrain: 24,
      boostRegen: 19,
      boostForce: 30000,
      downforce: 14.0,
    },
    body: {
      w: 1.25, h: 0.325, l: 2.625,
      ride: 0.85,
      track: 1.2, front: 1.775, rear: -1.75,
      style: 'hyper',
      cabin: { w: 0.925, h: 0.3, l: 1.4375, z: -0.10, y: 0.48 },
      lowWing: true,
    },
    stats: { SPEED: 10, ACCEL: 9, GRIP: 10, ARMOUR: 4, AIR: 7 },
  },
];

export const CAR_BY_ID = Object.fromEntries(CAR_TYPES.map((c) => [c.id, c]));

export function getCar(id) {
  return CAR_BY_ID[id] || CAR_TYPES[0];
}
